name: Kkyuni Actions
on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Ktlint
        run: ./gradlew spotlessCheck

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
